src/pages/hotel/AddHotelPage.js, src/pages/hotel/RoomModal.js
=> # 객실 생성시 호텔 아이디 받아오기

src/components/store/hotel/HotelAddSlice.js, src/components/store/hotel/RoomAddSlice.js, src/components/store/index.js, src/pages/hotel/AddHotelPage.js, src/pages/hotel/RoomModal.js
=> # 호텔 생성, 객실생성 리덕스 사용해서 리팩토링

src/components/hotel/HotelList.js, src/components/hotel/HotelSearchForm.js, src/components/store/hotel/HotelPageSlice.js, src/components/store/hotel/ReservationSlice.js, src/components/store/index.js, src/pages/hotel/HotelPage.js
=> 호텔 페이지, 예약 리덕스로 리팩토링 후 날짜데이터 포매팅

src/config/user/host-config.js, src/config/user/route-config.js, src/layout/user/MainNavigation.js, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss
=> 게시판 추가 / 관련 세팅 추가

src/components/hotel/HotelList.js, src/components/hotel/HotelList.module.scss, src/pages/hotel/HotelPage.js
=> 🐛 호텔 이미지 랜더링 수정

src/config/user/route-config.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss
=> # 게시글 상세글 추가 

src/components/hotel/HotelList.js, src/components/hotel/HotelSearchForm.js, src/components/hotel/Hoteldates.js, src/components/store/hotel/HotelAddSlice.js, src/components/store/hotel/RoomAddSlice.js, src/pages/hotel/AddHotelPage.js, src/pages/hotel/RoomModal.js
=> # 호텔 생성시 룸 여러개 생성 안되는거 해결, 날짜와 지역정보 입력하지 않으면 검색 불가, 날짜 입력시 몇월 며칠인지 렌더링

src/components/hotel/ReviewList.js, src/components/hotel/ReviewList.module.scss, src/components/hotel/RoomDetail.js, src/components/store/hotel/HotelReviewSlice.js
=> # 스텝2 리뷰 작성 및 스텝3 리뷰 렌더링

src/components/hotel/HotelList.js, src/components/hotel/RoomDetail.js, src/components/store/hotel/HotelAddSlice.js, src/pages/hotel/ModifyHotelPage.js, src/pages/hotel/ModifyHotelPage.module.scss
=> # 호텔 삭제, 수정기능 완성

src/components/hotel/HotelConfirmation.js, src/components/store/hotel/HotelReservationSlice.js, src/layout/user/MainNavigation.js
=> # 예약하기 완료 후 알람메일 오는거 해결

package-lock.json, src/config/user/route-config.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss, src/pages/community/BoardPostPage.js, src/pages/community/BoardPostPage.module.scss
=> Board/write Merge

src/config/user/route-config.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardPage.js
=> # 게시판 -로그인 안해도 보이도록 수정

src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss
=> # 유저 닉네임 / 프로필 표시

src/pages/shop/review/ReviewDetailPage.js, src/pages/shop/review/ReviewPage.js
=> app-img 리뷰 이미지 성고오오옹

src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss
=> # 게시판 디자인 수정

package-lock.json, src/pages/shop/review/ReviewDetailPage.js, src/pages/shop/review/ReviewPage.js, src/pages/shop/review/WriteReviewPage.js
WriteReviewPage
ReviewPage
ReviewDetailPage
수정
=> 사용자에 따라 리뷰 작성

src/components/hotel/BookingDetail.js, src/components/hotel/HotelConfirmation.js, src/components/store/hotel/ReservationSlice.js, src/pages/hotel/SeasonalityChart.js, src/pages/user/HotelRecords.js
=> # 예약 삭제기능 구현, 예약 그래프 구현, 코드 리팩토링

src/components/hotel/HotelList.module.scss, src/layout/user/Footer.module.scss, src/pages/Home.js, src/pages/Home.module.scss, src/pages/hotel/HotelPage.module.scss, src/pages/user/WelcomePage.js
=> ✅ 메인 인덱스 페이지 생성

src/config/user/host-config.js, src/config/user/route-config.js, src/layout/user/MainNavigation.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss, src/pages/community/BoardPostPage.js
=> Board reply 추가 

src/pages/shop/TreatsDetailModal.js, src/pages/shop/review/EditReviewPage.js, src/pages/shop/review/Review.module.scss, src/pages/shop/review/ReviewDetailPage.js, src/pages/shop/review/ReviewPage.js, src/pages/shop/review/WriteReviewPage.js
1. TreatsDetailModal.js 에 ReviewPage 추가 
2. 리뷰 디자인 수정
3. 본인 리뷰만 수정 가능하게 완료
4. 리뷰 리스트에서 더보기 기능 추가 
5. 리뷰 이미지 모달로 볼 수 있게 추가
=> 리뷰 디자인 및 코드 수정

src/components/store/hotel/RoomAddSlice.js, src/pages/hotel/ModifyRoomPage.js
=> # 룸 수정안되는 현상 수정완료

src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss, src/pages/community/BoardPostPage.js, src/pages/community/BoardPostPage.module.scss
=> Board/ 게시글 작성 시 이미지 추가 , 렌더링, 개별 게시글 랜더링 진행

src/config/user/route-config.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardEditPage.js, src/pages/community/BoardEditPage.module.scss
=> 게시글 수정 링크,페이지 추가

src/pages/shop/CartContent.js, src/pages/shop/order/OrderPage.js, src/pages/shop/order/OrderPage.module.scss
장바구니에 있는 값을 가져와서 오더페이지에 
상품이름, 
구독기간, 
패키지 리스트(5가지), 
상품 가격 및 남은 포인트 반영하기
+ 디자인 1차 작업
CartContent 에 yj 코드 추가 - 추가한 코드는 주석으로 표시함
=> 장바구니 값을 받아와서 오더 작업

src/config/user/route-config.js, src/pages/community/BoardDetailPage.js
=> # 대댓글 작성까지만 우선 추가

src/pages/community/BoardDetailPage.js
=> # 대댓글 수정 삭제 코드 추가

src/pages/shop/order/OrderDetail.js, src/pages/shop/order/OrderPage.js
간식 결제 후 차감된 포인트 마이페이지에 반영 
api user 엔터티, orderservice  적용시키니 되던 작업이 안되어서 롤백하고 작업함
=> 간식 결제 후 차감된 포인트 마이페이지에 반영 

src/pages/community/BoardEditPage.js
=> ▶︎게시글 수정 -버그 일부 고침 (이미지 추가+기존 내용 가져오는 코드 추가)

src/pages/shop/order/OrderPage.js
=> SHOP_URL 수정

src/pages/hotel/AddHotelPage.js, src/pages/hotel/ModifyHotelPage.js
=> # 호텔 프라이스 삭제

package-lock.json, package.json, src/config/user/host-config.js, src/pages/shop/TreatsDetailModal.js, src/pages/shop/order/OrderPage.js, src/pages/shop/review/EditReviewPage.js, src/pages/shop/review/Review.module.scss, src/pages/shop/review/ReviewPage.js, src/pages/shop/review/WriteReviewPage.js, src/pages/user/SnackReview.js, src/pages/user/SnackReview.module.scss
=> 리뷰 + 오저 수정작업

src/config/user/host-config.js, src/config/user/route-config.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss
각각의 유저는 게시글,댓글,대댓글 항목에 대해 한번씩 좋아요를 누를 수 있다.
모든 id를 가진 게시글,댓글,대댓글에 한해서 가능하게 구현
=> 게시글 - 좋아요 기능 추가 (댓글,대댓글도 처리)

src/pages/community/BoardPage.js
=> #좋아요 카운트 렌더링 추가(게시글 목록)

src/pages/community/BoardPage.js
=> #무한 스크롤 관련 안되는 부분 수정

src/pages/shop/order/EditInfoModal.js, src/pages/shop/order/OrderInfo.js, src/pages/shop/order/OrderPage.js, src/pages/shop/order/PaymentInfo.js, src/pages/shop/order/ProductInfo.js, src/pages/shop/order/scss/EditInfoModal.module.scss, src/pages/shop/order/scss/EditUserInfoModal.module.scss, src/pages/shop/order/scss/OrderDetail.module.scss, src/pages/shop/order/scss/OrderPage.module.scss, src/pages/shop/review/Review.module.scss, src/pages/shop/review/ReviewPage.js, src/pages/shop/review/WriteReviewPage.js, src/pages/user/SnackRecords.js, src/pages/user/SnackRecords.module.scss, src/pages/user/SnackReview.js, src/pages/user/SnackReview.module.scss
=>  디자인 수정 1차

src/pages/community/BoardPage.js
=> # 게시글 시간 표시 수정

src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss
=> 게시물 상세 페이지 댓글 정렬 필터 추가(최신순,등록순)

src/config/user/host-config.js, src/pages/community/BoardDetailPage.js, src/pages/community/BoardPage.js
=> Board url 재설정 

src/pages/shop/order/OrderDetail.js, src/pages/shop/order/scss/OrderDetail.module.scss
=> 오더 상세 디자인 다시 올림

src/pages/shop/review/EditReviewPage.js, src/pages/shop/review/ReviewDetailPage.js, src/pages/shop/review/ReviewPage.js
=> 리뷰에 호스트 컨피그 추가

src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardEditPage.js, src/pages/community/BoardEditPage.module.scss, src/pages/community/BoardPostPage.js, src/pages/community/BoardPostPage.module.scss
=> # 게시판 상세페이지,수정,게시글 페이지 디자인 및 네비게이션 추가(편의성 개선)

src/pages/shop/order/OrderInfo.js, src/pages/shop/order/scss/OrderDetail.module.scss, src/pages/shop/order/scss/OrderPage.module.scss, src/pages/shop/review/Review.module.scss, src/pages/shop/review/WriteReviewPage.js, src/pages/user/SnackReview.js, src/pages/user/SnackReview.module.scss
=> 리뷰 및 오더 반응형 작업

src/pages/shop/review/Review.module.scss, src/pages/shop/review/ReviewPage.js, src/pages/user/SnackReview.module.scss
=> 리뷰 디자인 수정2하고 최신순 별점순 스크립트 추가

src/components/community/FixedButtons.js, src/components/community/FixedButtons.module.scss, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss
=> # 게시글 목록 -  게시글 작성 버튼 스크롤 내릴 시 맨위로 올라가는 버튼 추가

src/components/auth/user/login/LoginForm.js
localStorage.setItem('provider', 'kakao');
=> 0820 카카오 로그인 에러 바로 수정

src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardPage.js
=> 🐛Board list bug fix

src/pages/shop/order/OrderDetail.js, src/pages/shop/order/OrderPage.js, src/pages/shop/order/PaymentInfo.js, src/pages/shop/order/scss/OrderDetail.module.scss, src/pages/shop/order/scss/OrderPage.module.scss, src/pages/shop/review/Review.module.scss, src/pages/user/SnackRecords.module.scss, src/pages/user/SnackReview.module.scss
=> 오더,리뷰 버튼 및 css 수정

src/pages/user/SnackReview.js
=> 리뷰 더보기 갯수 수정

src/pages/shop/order/scss/EditInfoModal.module.scss, src/pages/shop/order/scss/OrderDetail.module.scss, src/pages/user/SnackRecords.module.scss
=> 모바일쪽 css 수장

src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardEditPage.module.scss, src/pages/community/BoardPage.module.scss, src/pages/community/BoardPostPage.module.scss
=> ⚡️게시글 알림 메시지 모달 처리 (삭제 메시지, 공유하기 모달창 처리)

src/pages/community/BoardEditPage.js, src/pages/community/BoardEditPage.module.scss, src/pages/community/BoardPostPage.js, src/pages/community/BoardPostPage.module.scss
⚡️기능 개선- 게시글 작성] 
- 이미지 추가 시 미리보기 화면 제시 이미지 업로드 버튼 정리
- 이미지 업로드 버튼 취소해도 초기화 안되도록 처리
- 이미지는 한개씩 어느 위치에서도 다 불러올 수 있도록 처리
- 추가 잘못하면 개별 삭제 가능하도록 기능 처리
- 추가 디자인 적용
=> ⚡️기능 개선- 게시글 작성] - 이미지 업로드 개선, 미리보기 ,개별 추가 , 개별 삭제 기능 추가

src/pages/shop/order/OrderDetail.js, src/pages/shop/review/Review.module.scss, src/pages/shop/review/ReviewPage.js
리뷰 작성 후 이미지 portal 로 변경 및 css 수정
=> 0822 1 리뷰 작성 후 이미지 portal 로 변경 및 css 수정

src/pages/community/BoardDetailPage.js, src/pages/community/BoardDetailPage.module.scss, src/pages/community/BoardPostPage.module.scss
관리자 기능 추가
모든 게시글,댓글 대댓글의 수정 삭제 보이도록함
게시글 쓰기 내용 줄 바꿈 가능토록 처리
=> 관리자일 경우 모든 수정 삭제 보이도록함 (게시글,댓글,대댓글)/ 게시글 쓰기 내용 줄 바꿈 가능토록 처리

src/pages/shop/review/EditReviewPage.js, src/pages/shop/review/Review.module.scss, src/pages/shop/review/ReviewPage.js, src/pages/shop/review/WriteReviewPage.js, src/pages/user/SnackReview.js
=> 0823 - 누락된 주문취소 

src/pages/shop/order/OrderDetail.js, src/pages/shop/order/OrderPage.js, src/pages/shop/review/EditReviewPage.js, src/pages/shop/review/ReviewDetailPage.js, src/pages/shop/review/ReviewPage.js, src/pages/shop/review/WriteReviewPage.js, src/pages/user/SnackRecords.js, src/pages/user/SnackReview.js
=> 리뷰 오다 콘솔로그 주석 처리

src/pages/shop/review/WriteReviewPage.js, src/pages/user/SnackReview.js
=> 리뷰 작성하기 버튼 수정

src/config/user/route-config.js, src/pages/community/BoardEditPage.js, src/pages/community/BoardEditPage.module.scss, src/pages/community/BoardPage.js, src/pages/community/BoardPage.module.scss, src/pages/community/BoardPostPage.js, src/pages/community/BoardPostPage.module.scss
- 키워드, 커뮤니티렌더링(전체,각 태그 렌더링),관리자 태그 기능 추가
=> ⚡️게시판 -> 커뮤니티로 변경~⭐️

.github/workflows/deploy.yml, src/pages/hotel/ModifyRoomPage.js
=> # 불필요한 로그 제거 .env 파일 깃헙액션추가

src/config/user/route-config.js
=> ⚡️로그인 안해도 커뮤니티 접근할 수 있도록 수정

src/components/hotel/BookingDetail.js, src/config/user/route-config.js
=> # 비회원도 진입가능 결제페이지만 로그인했을때 가능하도록 수정

src/pages/shop/review/EditReviewPage.js, src/pages/shop/review/WriteReviewPage.js
=> " 리뷰 수정했을 때 이미지가 안보이는 부분 수정"

src/pages/community/BoardDetailPage.js
=> ⚡️Url http 되도록 수정

src/components/store/hotel/ReservationSlice.js, src/pages/hotel/SeasonalityChart.js
=> # 월별 예약현황 전체 가져오기
